# generated by datamodel-codegen:
#   filename:  https://ally-config-ui.dev.copilot.aws.inform-cloud.io/openapi.json
#   timestamp: 2025-10-20T13:23:06+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Extra, Field, constr


class AIModel(BaseModel):
    label: str = Field(..., description='Unique label of the AI model', title='Label')
    name: str = Field(
        ..., description='Name of the AI model (human-friendly)', title='Name'
    )
    description: str = Field(
        ..., description='Description of the AI model', title='Description'
    )
    enabled: bool = Field(
        ..., description='Indicates if the AI model is enabled', title='Enabled'
    )


class AWSLogDataDetails(BaseModel):
    log_data: List[Dict[str, Any]] = Field(
        ..., description='List of log data entries', title='Log Data'
    )
    session_ids: Dict[str, Dict[str, Any]] = Field(
        ...,
        description='Dictionary of session IDs with timestamps',
        title='Session Ids',
    )


class AWSLogDataFilter(BaseModel):
    log_group: str = Field(..., description='Log group in AWS', title='Log Group')
    session_id: Optional[str] = Field(
        None, description='Session ID for filtering logs', title='Session Id'
    )
    start_time: str = Field(
        ..., description='Start time for log retrieval', title='Start Time'
    )
    end_time: str = Field(
        ..., description='End time for log retrieval', title='End Time'
    )


class AcceptableResponsesSummary(BaseModel):
    acceptable: int = Field(..., title='Acceptable')
    unacceptable: int = Field(..., title='Unacceptable')
    no_response: int = Field(..., title='No Response')
    ratio: Optional[float] = Field(None, title='Ratio')


class ActionMatch(BaseModel):
    precision: str = Field(..., title='Precision')
    recall: str = Field(..., title='Recall')
    f1: Optional[float] = Field(None, title='F1')


class AllyAuthorizationConfig(BaseModel):
    type: str = Field('ally', const=True, title='Type')


class Attachment(BaseModel):
    mime_type: str = Field(..., title='Mime Type')
    data: str = Field(..., title='Data')


class BearerAuth(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Literal['bearer'] = Field(..., const=True, title='Type')
    token: str = Field(..., title='Token')


class BearerForwardAuth(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Literal['bearer-forward'] = Field(..., const=True, title='Type')


class BertScore(BaseModel):
    precision: float = Field(..., title='Precision')
    recall: float = Field(..., title='Recall')
    f1: float = Field(..., title='F1')


class BodyUploadFileToS3ApiUploadToS3Post(BaseModel):
    files: bytes = Field(..., title='Files')


class CapabilitiesResponse(BaseModel):
    keycloak_url: str = Field(
        ..., description='URL of the Keycloak server', title='Keycloak Url'
    )
    keycloak_realm: str = Field(
        ..., description='Realm in Keycloak', title='Keycloak Realm'
    )
    keycloak_client_id: str = Field(
        ..., description='Client ID for Keycloak', title='Keycloak Client Id'
    )
    ally_server_domain: str = Field(
        ..., description='Domain of the Ally server', title='Ally Server Domain'
    )
    ally_server_domain_local: Optional[str] = Field(
        None,
        description='Local domain of the Ally server',
        title='Ally Server Domain Local',
    )
    ai_knowledge_host: str = Field(
        ..., description='Host for AI knowledge', title='Ai Knowledge Host'
    )


class ChatScore(BaseModel):
    match: Optional[int] = Field(None, title='Match')
    comment: Optional[str] = Field(None, title='Comment')


class ClientCallingPlugin(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str = Field('ClientCalling', const=True, title='Type')


class CodeExecutionPlugin(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str = Field('CodeExecution', const=True, title='Type')
    base_url: str = Field(..., title='Base Url')
    token: Optional[str] = Field(None, title='Token')


class ConfigHistoryItem(BaseModel):
    name: str = Field(
        ..., description='Name of the configuration history item', title='Name'
    )
    id: Optional[str] = Field(
        None, description='ID of the configuration history item', title='Id'
    )
    label: Optional[str] = Field(
        None, description='Label of the configuration history item', title='Label'
    )


class ConversationEntry(BaseModel):
    role: str = Field(
        ...,
        description='Role in the conversation (e.g., user or assistant)',
        title='Role',
    )
    content: Any = Field(
        ..., description='Content of the conversation entry', title='Content'
    )
    attachments: Optional[List[Attachment]] = Field(
        None,
        description='List of attachments in the conversation entry',
        title='Attachments',
    )
    id: str = Field(..., description='ID of the conversation entry', title='Id')
    datetime: str = Field(
        ..., description='Timestamp of the conversation entry', title='Datetime'
    )
    update: Optional[str] = Field(
        None,
        description='A human-readable update message for the user when calling tools',
        title='Update',
    )


class CostGraphSnapshotResponse(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[str] = Field(
        None,
        description='Base64 encoded string representing the snapshot image',
        title='Data',
    )


class DashboardRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    month: Optional[int] = Field(None, description='Month for the data', title='Month')
    unit: str = Field(
        ..., description='Unit of measurement (e.g., tokens or euro)', title='Unit'
    )


class DeepEvalMetric(BaseModel):
    score: float = Field(..., title='Score')
    reason: str = Field(..., title='Reason')


class DeepEvalScores(BaseModel):
    correctness: DeepEvalMetric
    answer_relevancy: DeepEvalMetric


class DefaultAuthorizationConfig(BaseModel):
    type: str = Field('defaults', const=True, title='Type')


class DialogTestCase(BaseModel):
    name: str = Field(..., title='Name')
    description: Optional[str] = Field('', title='Description')
    continues: Optional[str] = Field(None, title='Continues')
    user_input: str = Field(..., title='User Input')
    expected_actions: Optional[List] = Field(None, title='Expected Actions')
    expected_response: Optional[str] = Field(None, title='Expected Response')


class DialogTestCaseResult(BaseModel):
    test_case: str = Field(..., title='Test Case')
    status: Optional[str] = Field(None, title='Status')
    messages: Optional[List[Dict[str, Any]]] = Field(None, title='Messages')
    actual_actions: Optional[List] = Field(None, title='Actual Actions')


class DialogTestSuite(BaseModel):
    name: str = Field(..., title='Name')
    description: Optional[str] = Field('', title='Description')
    test_cases: List[DialogTestCase] = Field(..., title='Test Cases')


class DialogTestSuiteResult(BaseModel):
    test_suite: str = Field(..., title='Test Suite')
    test_case_results: Optional[List[DialogTestCaseResult]] = Field(
        None, title='Test Case Results'
    )


class EndpointAttributes(BaseModel):
    dep_name: str = Field(..., description='Model of the endpoint', title='Dep Name')
    instructions: Optional[str] = Field(
        None, description='Instructions for the endpoint', title='Instructions'
    )
    default_message: str = Field(
        ..., description='Default message for the endpoint', title='Default Message'
    )


class EndpointMetadata(BaseModel):
    display_name: Optional[str] = Field(
        None, description='Human-readable name of the endpoint', title='Display Name'
    )
    description: Optional[str] = Field(
        None, description='Description of the endpoint', title='Description'
    )
    project_number: Optional[str] = Field(
        None, description='Project number of the endpoint', title='Project Number'
    )


class EndpointMetadataRequest(BaseModel):
    endpoint: str = Field(
        ..., description='Endpoint to get metadata for', title='Endpoint'
    )


class EndpointRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')


class EndpointsResponseEntry(BaseModel):
    prefix: str = Field(..., description='Prefix of the endpoints', title='Prefix')
    suffixes: List[str] = Field(
        ..., description='List of endpoint suffixes', title='Suffixes'
    )
    metadatas: Optional[List[EndpointMetadata]] = Field(
        None,
        description='List of Metadata of the endpoints (aligned with suffixes)',
        title='Metadatas',
    )


class ErrorResponse(BaseModel):
    detail: str = Field(..., description='Error message', title='Detail')


class HistoryReduction(BaseModel):
    class Config:
        extra = Extra.forbid

    old_calls: Optional[bool] = Field(None, title='Old Calls')
    bad_calls: Optional[bool] = Field(None, title='Bad Calls')
    large_api_response: Optional[bool] = Field(None, title='Large Api Response')


class KeycloakAuth(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Literal['keycloak'] = Field(..., const=True, title='Type')
    server_url: str = Field(..., title='Server Url')
    realm_name: str = Field(..., title='Realm Name')
    client_id: Union[str, int] = Field(..., title='Client Id')


class ListEndpointsRequest(BaseModel):
    prefix: Optional[str] = Field(
        None, description='Prefix of the endpoints to list', title='Prefix'
    )


class Message(BaseModel):
    role: str = Field(..., title='Role')
    content: Optional[Any] = Field(None, title='Content')
    attachments: Optional[List[Attachment]] = Field(None, title='Attachments')
    correlation_id: Optional[str] = Field(None, title='Correlation Id')
    datetime: Optional[str] = Field(None, title='Datetime')
    tool_calls: Optional[List] = Field(None, title='Tool Calls')
    tool_call_id: Optional[str] = Field(None, title='Tool Call Id')
    name: Optional[str] = Field(None, title='Name')
    is_client_call: Optional[bool] = Field(False, title='Is Client Call')
    update: Optional[str] = Field(None, title='Update')
    has_next: Optional[bool] = Field(True, title='Has Next')


class NoAuth(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Literal['none'] = Field(..., const=True, title='Type')


class NoAuthorizationConfig(BaseModel):
    type: str = Field('allow', const=True, title='Type')


class OpenIDAuthorizationConfig(BaseModel):
    type: str = Field('openid', const=True, title='Type')
    openid_provider_uri: Optional[constr(regex=r'^(https?://)')] = Field(
        None,
        description="The URI of the OpenID provider to verify the OpenID token. This commonly ends with '/.well-known/openid-configuration'.",
        title='Openid Provider Uri',
    )
    server_url: Optional[constr(regex=r'^(https?://)')] = Field(
        None,
        description='The common URL of the OpenID provider. Sometimes with /auth sometimes without. Use this together with realm_name instead of the openid_provider_uri to build the full URL of the OpenID provider.',
        title='Server Url',
    )
    realm_name: Optional[str] = Field(
        None,
        description="The realm of the OpenID provider. 'inform-ai' for INFORM AI keycloak.",
        title='Realm Name',
    )
    openid_audience: Optional[str] = Field(
        None,
        description='The audience of the OpenID token. This is used to validate the token.',
        title='Openid Audience',
    )
    openid_methods: Optional[List[str]] = Field(
        [
            'HS256',
            'HS384',
            'HS512',
            'RS256',
            'RS384',
            'RS512',
            'ES256',
            'ES384',
            'ES512',
            'PS256',
            'PS384',
            'PS512',
        ],
        description='The OpenAI methods which are allowed to access the Ally server.',
        title='Openid Methods',
    )


class PermissionData(BaseModel):
    id: str = Field(..., description='internal name of the permission', title='Id')
    short: str = Field(..., description='short name of the permission', title='Short')
    long: str = Field(
        ..., description='longer description of the permission', title='Long'
    )
    granted: bool = Field(
        ...,
        description='flag indicating whether the permission is granted',
        title='Granted',
    )


class PermissionRoleRequest(BaseModel):
    resource_name: str = Field(
        ..., description='Name of the resource', title='Resource Name'
    )
    role: str = Field(..., description='Name of the role to update', title='Role')
    permission: str = Field(
        ..., description='ID of the permission to add or remove', title='Permission'
    )


class Rating(BaseModel):
    endpoint: str = Field(
        ..., description='Endpoint of the interaction.', title='Endpoint'
    )
    rating: int = Field(..., description='Rating value from -1 to 1.', title='Rating')
    user_name: Optional[str] = Field(
        None, description='The name of the user giving feedback.', title='User Name'
    )
    model_name: Optional[str] = Field(
        None, description='The name of the used model.', title='Model Name'
    )
    session_id: Optional[str] = Field(
        None, description='Session ID of the user.', title='Session Id'
    )
    history: Optional[List[Message]] = Field(
        None, description='List of accumulated messages.', title='History'
    )
    timestamp: Optional[float] = Field(None, title='Timestamp')


class RatingsRequest(BaseModel):
    endpoint: Optional[str] = Field(None, title='Endpoint')
    start: Optional[datetime] = Field(None, title='Start')
    end: Optional[datetime] = Field(None, title='End')


class Response(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Any = Field(None, description='Response data', title='Data')


class ResponseMatch(BaseModel):
    bleu_score: float = Field(..., title='Bleu Score')
    bert_score: Optional[BertScore] = None
    deepeval: Optional[DeepEvalScores] = None
    chat_score: Optional[ChatScore] = None
    has_acceptable_response: Optional[bool] = Field(
        None, title='Has Acceptable Response'
    )


class ResponseAWSLogDataDetails(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[AWSLogDataDetails] = Field(None, description='Response data')


class ResponseEndpointMetadata(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[EndpointMetadata] = Field(None, description='Response data')


class ResponseEndpointsResponseEntry(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[EndpointsResponseEntry] = Field(None, description='Response data')


class ResponseDictDateList(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[Dict[str, List]] = Field(
        None, description='Response data', title='Data'
    )


class ResponseListAIModel(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[AIModel]] = Field(
        None, description='Response data', title='Data'
    )


class ResponseListConfigHistoryItem(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[ConfigHistoryItem]] = Field(
        None, description='Response data', title='Data'
    )


class ResponseListRating(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[Rating]] = Field(
        None, description='Response data', title='Data'
    )


class ResponseListStr(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[str]] = Field(None, description='Response data', title='Data')


class ResponseStr(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[str] = Field(None, description='Response data', title='Data')


class RoleData(BaseModel):
    role: str = Field(..., description='name of the role', title='Role')
    members: List[str] = Field(
        ..., description='list of users in the role', title='Members'
    )
    permissions: List[PermissionData] = Field(
        ...,
        description='list of permissions: pair or name of granted flag',
        title='Permissions',
    )


class RoleRequest(BaseModel):
    resource_name: str = Field(
        ..., description='Name of the resource', title='Resource Name'
    )
    role: str = Field(..., description='Name of the role to update', title='Role')


class SessionFilter(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    start_time: str = Field(
        ..., description='Start time of the session', title='Start Time'
    )
    end_time: str = Field(..., description='End time of the session', title='End Time')


class StaticBearerAuthorizationConfig(BaseModel):
    type: str = Field('static', const=True, title='Type')
    token: str = Field(
        ...,
        description='A static bearer token which is allowed to access the Ally server.',
        title='Token',
    )


class StoredTestSuite(BaseModel):
    suite: DialogTestSuite
    timestamp: str = Field(..., title='Timestamp')
    version: Optional[str] = Field(None, title='Version')


class SummaryStatistics(BaseModel):
    count: int = Field(..., title='Count')
    mean: Optional[float] = Field(None, title='Mean')
    stdev: Optional[float] = Field(None, title='Stdev')
    median: Optional[float] = Field(None, title='Median')
    min: Optional[float] = Field(None, title='Min')
    max: Optional[float] = Field(None, title='Max')


class SummaryWithReason(BaseModel):
    score: SummaryStatistics
    reason: Optional[str] = Field(None, title='Reason')


class TestSuiteContentsRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    test_suite_name: str = Field(
        ...,
        description='Name of test suite for the evaluation',
        title='Test Suite Name',
    )
    test_cases: List[DialogTestCase] = Field(
        ..., description='List of test cases to add or update', title='Test Cases'
    )


class TestSuiteRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    test_suite_name: str = Field(
        ...,
        description='Name of test suite for the evaluation',
        title='Test Suite Name',
    )


class UpdateEndpointMetadataRequest(BaseModel):
    endpoint: str = Field(
        ..., description='Endpoint to get metadata for', title='Endpoint'
    )
    metadata: EndpointMetadata = Field(..., description='Metadata to update')


class UserRoleRequest(BaseModel):
    resource_name: str = Field(
        ..., description='Name of the resource', title='Resource Name'
    )
    role: str = Field(..., description='Name of the role to update', title='Role')
    user: str = Field(..., description='Username of the user', title='User')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class XAPIKeyHeaderAuth(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Literal['x-api-key-header'] = Field(..., const=True, title='Type')


class ActionMatchSummary(BaseModel):
    f1: SummaryStatistics


class AiKnowledgePlugin(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str = Field('AiKnowledge', const=True, title='Type')
    collections: List[
        constr(regex=r'^[a-zA-Z_][a-zA-Z0-9_]*$', min_length=8, max_length=62)
    ] = Field(..., title='Collections')
    host: Optional[str] = Field(
        None, description='Host of the AiKnowledge HTTP server', title='Host'
    )
    authorization: Optional[
        Union[BearerAuth, BearerForwardAuth, KeycloakAuth, NoAuth, XAPIKeyHeaderAuth]
    ] = Field(
        None,
        description='Authorization model for the AiKnowledge HTTP server. Defaults to bearer-forward if not specified.',
        title='Authorization',
    )
    document_metadata: Optional[List[str]] = Field(
        [], description='document metadata fields to get', title='Document Metadata'
    )
    document_limit: Optional[int] = Field(
        40,
        description='max number of documents for which to get metadata',
        title='Document Limit',
    )
    query_tool_description: Optional[str] = Field(
        'Query a text database based on a given string. The top 10 results will be returned in a pseudo-list format with a line of hashes separating each result. Along with the text content, the source of the document will be displayed. Where possible reference the source document by name.',
        description='Custom query tool description, exposed to the languagemodel to help it decide when to use this tool.',
        title='Query Tool Description',
    )
    metadata_tool_description: Optional[str] = Field(
        'Retrieve document-level metadata fields. The results will include up to 40 documents per collection.',
        description='Custom metadata tool description, exposed to the languagemodel to help it decide when to use this tool.',
        title='Metadata Tool Description',
    )
    fragment_limit: Optional[int] = Field(
        10,
        description='max number of fragments to return for the query results',
        title='Fragment Limit',
    )


class BertScoreSummary(BaseModel):
    precision: SummaryStatistics
    recall: SummaryStatistics
    f1: SummaryStatistics


class Conversation(BaseModel):
    session_id: str = Field(
        ..., description='ID of the conversation session', title='Session Id'
    )
    messages: List[ConversationEntry] = Field(
        ..., description='List of conversation messages', title='Messages'
    )
    last_updated: str = Field(
        ...,
        description='Last updated timestamp of the conversation',
        title='Last Updated',
    )


class CreateEndpointRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    endpoint_attributes: Optional[EndpointAttributes] = Field(
        None, description='Attributes of the endpoint'
    )
    endpoint_metadata: Optional[EndpointMetadata] = Field(
        None, description='Metadata of the endpoint'
    )


class DeepEvalSummary(BaseModel):
    correctness: SummaryWithReason
    relevancy: SummaryWithReason


class DialogTestCaseEvaluation(BaseModel):
    test_case: str = Field(..., title='Test Case')
    response_match: Optional[ResponseMatch] = None
    action_match: Optional[ActionMatch] = None


class DialogTestSuiteEvaluation(BaseModel):
    test_suite: str = Field(..., title='Test Suite')
    test_case_evaluations: Optional[List[DialogTestCaseEvaluation]] = Field(
        [], title='Test Case Evaluations'
    )


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class OpenAPIPlugin(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str = Field('OpenAPI', const=True, title='Type')
    authorization: Union[
        BearerAuth, BearerForwardAuth, KeycloakAuth, NoAuth, XAPIKeyHeaderAuth
    ] = Field(..., discriminator='type', title='Authorization')
    openapi_spec: str = Field(..., title='Openapi Spec')
    base_url: str = Field(..., title='Base Url')
    get_only: Optional[bool] = Field(None, title='Get Only')
    api_desc: Optional[str] = Field(None, title='Api Desc')
    corrections: Optional[List[str]] = Field(None, title='Corrections')


class ResponseMatchSummary(BaseModel):
    bleu_score: SummaryStatistics
    bert_score: Optional[BertScoreSummary] = None
    chat_score: Optional[SummaryStatistics] = None
    deepeval: Optional[DeepEvalSummary] = None


class ResponseStoredTestSuite(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[StoredTestSuite] = Field(None, description='Response data')


class ResponseListConversation(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[Conversation]] = Field(
        None, description='Response data', title='Data'
    )


class ResponseListStoredTestSuite(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[List[StoredTestSuite]] = Field(
        None, description='Response data', title='Data'
    )


class DialogTestSuiteEvaluationSummary(BaseModel):
    test_suite: str = Field(..., title='Test Suite')
    num_test_cases: int = Field(..., title='Num Test Cases')
    num_tests_completed: int = Field(..., title='Num Tests Completed')
    response_match: ResponseMatchSummary
    acceptable_responses: Optional[AcceptableResponsesSummary]
    action_match: ActionMatchSummary


class EngineConfigInput(BaseModel):
    class Config:
        extra = Extra.forbid

    dep_name: str = Field(
        ...,
        description="OpenAI model deployment name, such as 'gpt-4o-mini'",
        title='Dep Name',
    )
    temperature: Optional[float] = Field(
        0.0,
        description='Temperature for the LLM, default is 0. Set to a negative value to use the default temperature of the model.',
        title='Temperature',
    )
    history_reduction: Optional[HistoryReduction] = None
    instructions: Optional[str] = Field(
        None,
        description='Instructions for the LLM, default instructions will be used if empty',
        title='Instructions',
    )
    default_message: Optional[str] = Field(
        None,
        description='Predefined first message that will be sent to the user,         default message will be used if empty',
        title='Default Message',
    )
    initial_prompt_suggestions: Optional[List[str]] = Field(
        None,
        description='Predefined suggestions for initial user',
        title='Initial Prompt Suggestions',
    )
    plugins: Optional[
        Dict[
            constr(regex=r'^[a-zA-Z0-9-]+$'),
            Union[
                AiKnowledgePlugin,
                ClientCallingPlugin,
                CodeExecutionPlugin,
                OpenAPIPlugin,
            ],
        ]
    ] = Field(
        None,
        description='dictionary of plugin configurations, keyed by plugin name',
        title='Plugins',
    )


class EngineConfigOutput(BaseModel):
    class Config:
        extra = Extra.forbid

    dep_name: str = Field(
        ...,
        description="OpenAI model deployment name, such as 'gpt-4o-mini'",
        title='Dep Name',
    )
    temperature: Optional[float] = Field(
        0.0,
        description='Temperature for the LLM, default is 0. Set to a negative value to use the default temperature of the model.',
        title='Temperature',
    )
    history_reduction: Optional[HistoryReduction] = None
    instructions: Optional[str] = Field(
        None,
        description='Instructions for the LLM, default instructions will be used if empty',
        title='Instructions',
    )
    default_message: Optional[str] = Field(
        None,
        description='Predefined first message that will be sent to the user,         default message will be used if empty',
        title='Default Message',
    )
    initial_prompt_suggestions: Optional[List[str]] = Field(
        None,
        description='Predefined suggestions for initial user',
        title='Initial Prompt Suggestions',
    )
    plugins: Optional[
        Dict[
            constr(regex=r'^[a-zA-Z0-9-]+$'),
            Union[
                AiKnowledgePlugin,
                ClientCallingPlugin,
                CodeExecutionPlugin,
                OpenAPIPlugin,
            ],
        ]
    ] = Field(
        None,
        description='dictionary of plugin configurations, keyed by plugin name',
        title='Plugins',
    )


class Evaluation(BaseModel):
    result_data: DialogTestSuiteResult
    eval_data: DialogTestSuiteEvaluation
    summary: DialogTestSuiteEvaluationSummary


class LenientConfig(BaseModel):
    id: Optional[str] = Field(None, description='ID of the configuration', title='Id')
    name: str = Field(..., description='Name of the configuration', title='Name')
    label: Optional[str] = Field(
        None, description='Label of the configuration', title='Label'
    )
    engine_data: Union[Dict[str, Any], EngineConfigOutput] = Field(
        ...,
        description='Engine data for the configuration. This should follow ally_core.datamodel.EngineConfig, but the database may have invalid entries which could not be retrieved is this was strict.',
        title='Engine Data',
    )


class ResponseEvaluation(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[Evaluation] = Field(None, description='Response data')


class ResponseLenientConfig(BaseModel):
    success: bool = Field(
        ..., description='Indicates if the request was successful', title='Success'
    )
    error_msg: Optional[str] = Field(
        None, description='Error message if the request failed', title='Error Msg'
    )
    data: Optional[LenientConfig] = Field(None, description='Response data')


class EndpointConfigRequest(BaseModel):
    endpoint: str = Field(..., description='Name of the endpoint', title='Endpoint')
    config_data: Optional[EngineConfigInput] = Field(
        None, description='configuration data'
    )
    config_id: Optional[str] = Field(
        None,
        description='ID of the configuration to fetch, or None for the currently active one',
        title='Config Id',
    )
