from pydantic_ai import Agent, RunContext
from .model_config import ModelConfiguration
from meta_ally.util.system_prompts import SystemPrompts
from typing import Any, List, Optional
from pydantic import BaseModel, Field

from pydantic_ai import ModelMessage


class ConversationVariant(BaseModel):
    """
    Structured output model for conversation variants generated by the variation agent.

    """

    messages: List[ModelMessage] = Field(
        description="List of messages in the conversation variant, maintaining the original flow"
    )


def create_variation_agent(
    previous_variants: Optional[List[Any]] = None,
) -> Agent[Any, ConversationVariant]:
    """
    Creates and returns a variation agent for generating diverse outputs.

    Args:
        previous_variants: Optional list of previously generated MessageHistoryCase variants
                          to avoid creating duplicates

    Returns:
        Agent: An instance of the variation agent with access to previous variants.
    """
    if previous_variants is None:
        previous_variants = []

    model = ModelConfiguration(deployment_name="gpt-4.1").create_model()

    variation_agent = Agent(
        name="Variation Agent",
        system_prompt=SystemPrompts.CONVERSATION_VARIANT_GENERATOR,
        model=model,
        output_type=ConversationVariant,
        output_retries=3,
    )

    @variation_agent.tool
    def get_previous_variants(ctx: RunContext[Any]) -> str:
        """Get information about all previously generated variants to avoid creating duplicates.

        Returns:
            A formatted string containing all previous variant conversations, or a message
            indicating no previous variants exist.
        """
        if not previous_variants:
            return "No previous variants have been generated yet. This is the first variant."

        result = f"There are {len(previous_variants)} previous variants. Ensure your new variant is different from all of these:\n\n"

        for idx, variant in enumerate(previous_variants, 1):
            result += f"--- Previous Variant #{idx} ---\n"
            result += variant.json() + "\n"

        return result

    return variation_agent
