from pydantic_ai import Agent
from .agent_factory import AgentFactory
from src.util.system_prompts import SystemPrompts
from typing import Any, List
from pydantic import BaseModel, Field

from pydantic_ai import ModelMessage


class ConversationVariant(BaseModel):
    """
    Structured output model for conversation variants generated by the variation agent.
    
    """
    
    messages: List[ModelMessage] = Field(
        description="List of messages in the conversation variant, maintaining the original flow"
    )



def create_variation_agent() -> Agent[Any, ConversationVariant]:
    """
    Creates and returns a variation agent for generating diverse outputs.

    Returns:
        Agent: An instance of the variation agent.
    """
    factory = AgentFactory()
    model = factory.create_azure_model_config(deployment_name="gpt-4.1").create_model()

    variation_agent = Agent(
        name="Variation Agent",
        system_prompt=SystemPrompts.CONVERSATION_VARIANT_GENERATOR,
        model=model,
        output_type=ConversationVariant,
        output_retries=3
    )

    return variation_agent
